### PR TITLE
Godot 4 Hotfix + Bug fixes and cleanup

### PR DESCRIPTION
**Pull request by ZachAR3**
Running on Godot 4.0.2 there are a few issues present resulting in an inability to use this plugin. This PR aims to resolve those by changing a few names and type script, along with rewriting the tweens to work with the new system. WARNING due to sub-optimal physics in Godot 4 at the moment, the explosion script acts sporadically, and the piles of rigidbodies twitch far more then in Godot 3. This will hopefully be fixed in a future patch, but for the time being the explosion likely needs some parameter changes. I may work on those once I have more free-time if no one has done so already.

### CODE REVIEW

**Comment by Jummit** [comment]
Thanks for taking the time! I think the best course of action would be to get the 4.0 version of the plugin to be stable and then release it as the main version.

**Comment by ZachAR3** [comment]
Fair enough, I would still merge this with master since currently master is unusable other than on old 4.0 betas; but I understand waiting to re-release it on the market place. Any pressing issues preventing the release on the market I can take a look at?

**Comment by ZachAR3** [comment]
> Thanks for taking the time! I think the best course of action would be to get the 4.0 version of the plugin to be stable and then release it as the main version.

It also seems the issue I was experiencing with the rigid body seems to be an issue with the position property of impulse on the first tick of the rigid body.  I opened an issue request [here](https://github.com/godotengine/godot/issues/75934), hopefully it will be fixed soon so the work around can be removed.

**Comment by Jummit** [comment]
Merging, but I might push some changes after I look over this in detail.

**Pull request merged**
