### PR TITLE
Fixes the pause that happens when calling the destruction function

### PR DESCRIPTION
**Pull request by mgrigajtis**
There was a pause that was happening when the destruction function was called, this fixes that.

### CODE REVIEW

**Comment by Jummit** [comment]
Thanks for the PR! This will load shards into memory for every destructible object, which could be a problem if you have a lot of them. I think it would be best to add an enum `load_shards` with values `On destroy` and `On ready` to allow users to configure this.

**Comment by ZachAR3** [comment]
> Thanks for the PR! This will load shards into memory for every destructible object, which could be a problem if you have a lot of them. I think it would be best to add an enum `load_shards` with values `On destroy` and `On ready` to allow users to configure this.

This seems like an easy addition, do you want an enum contating `On destroy` and `On ready` options for every single shard or a global option?

**Comment by Jummit** [comment]
> > Thanks for the PR! This will load shards into memory for every destructible object, which could be a problem if you have a lot of them. I think it would be best to add an enum `load_shards` with values `On destroy` and `On ready` to allow users to configure this.
> 
> This seems like an easy addition, do you want an enum contating `On destroy` and `On ready` options for every single shard or a global option?

The best solution would be to create the shards in a separate thread. No option required and no stutters.

**Comment by ZachAR3** [comment]
> > > Thanks for the PR! This will load shards into memory for every destructible object, which could be a problem if you have a lot of them. I think it would be best to add an enum `load_shards` with values `On destroy` and `On ready` to allow users to configure this.
> > 
> > 
> > This seems like an easy addition, do you want an enum contating `On destroy` and `On ready` options for every single shard or a global option?
> 
> The best solution would be to create the shards in a separate thread. No option required and no stutters.

This seems to be fixed by removing the function in issue #7 but if that function is necessary I can throw it on another thread.

**Comment by Jummit** [comment]
This problem is fixed in the latest version.

**Pull request closed without merging**
